import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Snippets from "../components/Snippets";
import useSWR from "swr";
import Link from "next/link";

export default function Home() {
  const { data: snippets, mutate } = useSWR("api/snippets");
  return (
    <div className={styles.container}>
      <Head>
        <title>View Snippet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Reusable Code Snippets</h1>

        <p className={styles.info}>Add your code snippets here...</p>
        <Link href="/upload">
          <button>Create New Snippet</button>
        </Link>

        {snippets &&
          snippets.map((snippet) => (
            <Snippets
              key={snippet.id}
              snippet={snippet}
              snippetDeleted={mutate}
            />
          ))}
      </main>
    </div>
  );
}
